- bin/cli.sh
- bin/config.sh
- bin/run.sh
- bin/setup.sh
- rdp
we will also call datasets `recipes`, which will mirror how we set up ceqr
> setting up repo

- recipes/betanyc/create.sql
Create separate category and subcategory fields for betaNYC
> Recategorize BetaNYC

- bin/config.sh
- recipes/_helper/geo.py
- recipes/betanyc/build.py
- recipes/betanyc/create.sql
- recipes/betanyc/runner.sh
- recipes/foursquare/asof.py
- recipes/foursquare/create.sql
- recipes/foursquare/runner.sh
- Ingestion complete (5 seperate github sources concat to 1)
- Geocoding complete
> WIP - Betanyc

- .github/workflows/main.yml
Create issue with [build] and the names of the datasets to trigger a build.
> CI: Workflow for issue-triggered builds

- recipes/foursquare/create.sql
- recipes/foursquare/runner.sh
#23
Modify foursquare output to make rows summable
> Split & pivot foursquare

- recipes/upsolve/build.py
still need:
- adding `gspread` and `oauth2client` to Dockerfile
> adding google sheet pulling for upsolve

- .gitignore
- Dockerfile
- bin/axway.sh
- bin/config.sh
- bin/run.sh
- recipes/betanyc/runner.sh
- recipes/cuebiq/create.sql
- recipes/cuebiq/create_daily.sql
- recipes/cuebiq/create_weekly.sql
- recipes/cuebiq/runner.sh
- recipes/kinsa/create.sql
- recipes/kinsa/runner.sh
- need to add config
- cuebiq has two data sets with different update frequency
> adding cuebiq and kinsa pipelines

- .gitignore
- recipes/street_easy/build_rental_sales_index.py
- recipes/street_easy/create_rental_sales_index.sql
- recipes/street_easy/runner.sh
```sql
CREATE TABLE street_easy_rental_sales_index."2020-08-12" (
month date,
borough text,
sales_index numeric,
rental_index numeric
);
```
> adding street easy price index

- recipes/street_easy/build.py
- recipes/street_easy/runner.sh
- recipes/upsolve/build.py
- recipes/upsolve/create.sql
- recipes/upsolve/runner.sh
no_of_pending_listings -> no_of_pending_rental_listings
drop columns if not exists
> fixing bugs for street_Easy and upsolve

- recipes/oats/get_data.py
- recipes/oats/runner.sh
.env is updated with GDRIVE_OATS folder id
> pulling oats from google drive

- recipes/ioby/build.py
> #53: Change ioby filenames to match axway pull

- recipes/usl/build.py
- recipes/usl/create.sql
- recipes/usl/runner.sh
#4 
+ Read input data from a local csv (this is a static flat file that got sent via email --  converted from xlsx)
+ Extract and sort relevant columns for transfer postgres
+ Export to sys to transfer to postgres
+ Data mapping and cleaning
+ Combine radio-button and text input columns where relevant
+ Check that zip codes are valid
+ Strip excess white space from concatenated options
+ Simplify/normalize some text answers
+ Version and export
> Urban System Lab

- .github/workflows/cuebiq_travelers.yml
- recipes/cuebiq/create_travelers.sql
- recipes/cuebiq/runner.sh
ETL for Cuebiq travelers dataset
Currently results in duplicates over county & origin_state for some of the records with reference date 2020-07-01 (not identical -- counts differ). Need to figure out why.
> Cuebiq travelers workflow

- bin/config.sh
- bin/sharepoint.py
- rdp
- requirements.txt
- do not merge yet because sharepoint urls are not added to the whitelist yet
- full functional replacement of "upload" in config.sh
> using sharepoint for upload

- rdptools/pyproject.toml
- rdptools/setup.py
package publishing using poetry
> finalize distribution scripts

- rdptools/pyproject.toml
- rdptools/rdptools/core.py
- rdptools/setup.py
- rewrite siteroot property
- bumping rdptools to 0.1.7
solving #81
> removing root folder listing so that we do not have permission conflict

- recipes/linkedin/runner.sh
linkedin.csv -> linkedin_nyc_hiringrate.csv
#97
> Normalize - Linkedin

- recipes/usl/create.sql
#85 
#95 
- adding borough and borocode
- zip -> zipcode
- date formating is in the correct format
> Normalize - USL (#85)

- recipes/opportunity_insights/create_daily.sql
- recipes/opportunity_insights/create_weekly.sql
- recipes/opportunity_insights/runner.sh
> Normalize Opportunity Insights

- recipes/upsolve/create.sql
- recipes/upsolve/runner.sh
> Upsolve Normalization

- .github/workflows/ioby.yml
- .github/workflows/oats.yml
- .github/workflows/opp_insights_daily.yml
- .github/workflows/opp_insights_weekly.yml
> Add workflows for oats, oppinsights, and ioby

- recipes/street_easy/create.sql
- recipes/street_easy/create_rental_sales_index.sql
- recipes/street_easy/init.sql
- recipes/street_easy/runner.sh
> Normalization - Streeteasy

- recipes/oats/build.py
- recipes/oats/create.sql
#76 
- Add borough fields, 
- rename zipcode field, and
- improve location logic so that only valid zipcodes have this field populated.
> OATS Standardization

- rdptools/rdptools/core.py
under class `Site`
```python
rdp.list_files_recursive
rdp.remove_folder_recursive
```
Will upgrade package version and republish to pypi once approved
> Rdptools removal operations

- rdptools/rdptools/core.py
- Reverts MODA-NYC/db-recovery-data-partnership#108
- still needs testing, revert for now
> Revert "Rdptools removal operations"

- recipes/foursquare/runner_county.sh
> Change foursquare.weekly_county to $NAME.weekly_county

- recipes/upsolve/runner.sh
Shapefile was not uploading because it was in the wrong directory
> Put shapefile in output directory

- recipes/cuebiq/create_daily.sql
- recipes/cuebiq/runner.sh
- recipes/cuebiq/runner_daily.sh
- recipes/cuebiq/runner_mobility.sh
- recipes/cuebiq/runner_travelers.sh
- recipes/cuebiq/runner_weekly.sh
note that transportation does not have naics and brand info #116
> fixing cuebiq daily and weekly, fixing naics code in cuebiq daily

- recipes/ioby/build.py
In order to process the new ioby data, the following needed to get changed:
- Manual removal of spaces in the filenames on axway
- Changing the relevant columns to pull for il4 because white space changed
> Ioby update

- recipes/opportunity_insights/build_daily.py
- recipes/opportunity_insights/create_daily.sql
Unclear if this data is permanently gone. This is a temp fix.
> Remove womply

- recipes/linkedin/create.sql
> LinkedIn: Change month_begin_date to year_month

- recipes/betanyc/create.sql
> BetaNYC: Add borocode field

- recipes/oats/create.sql
#127  `email_moly - > internet_wkly`
> email_moly - > internet_wkly

- recipes/ioby/create.sql
- recipes/ioby/runner.sh
> adding borocode and remove shapefiles

- recipes/opportunity_insights/create_daily.sql
> gps_resitential  -> gps_residential

- recipes/ioby/runner.sh
> adding as_of_date for ioby_count_by_zip

- recipes/foursquare/runner_zipcode.sh
```bash
psql $RDP_DATA -c "\COPY (
SELECT * FROM $NAME.latest
) TO stdout DELIMITER ',' CSV HEADER;" > foursquare_daily_zipcode_raw.csv
zip -9 foursquare_daily_zipcode_raw.zip foursquare_daily_zipcode_raw.csv
rm foursquare_daily_zipcode_raw.csv
```
> leaving all fields in foursquare_daily_zipcode_raw

- recipes/cuebiq/runner_mobility.sh
- recipes/cuebiq/runner_travelers.sh
> Cuebiq: Rename mobility and travelers tables

- .github/workflows/versions.yml
- bin/config.sh
- bin/run.sh
- bin/versions.py
- recipes/betanyc/runner.sh
- recipes/cuebiq/runner_daily.sh
- recipes/cuebiq/runner_mobility.sh
- recipes/cuebiq/runner_travelers.sh
- recipes/cuebiq/runner_weekly.sh
- recipes/foursquare/runner_county.sh
- recipes/foursquare/runner_zipcode.sh
- recipes/ioby/runner.sh
- recipes/kinsa/runner.sh
- recipes/linkedin/runner.sh
- recipes/oats/runner.sh
- recipes/opportunity_insights/runner.sh
- recipes/street_easy/runner.sh
- recipes/upsolve/runner.sh
- recipes/usl/runner.sh
#142 
thought process: 
- upload a versioning.txt for each scheduled pipeline to shared document folder
- write a separate process to combine all these txt files to a master versioning csv file
schema follows: 
- Partner
- Subproduct
- Version
- Last Updated
Once ready:
- merge
- rerun all pipelines
- done! (on a hourly cycle)
> Adding scripts to assist upload

- recipes/met/create_attendance.sql
- recipes/met/create_membership.sql
- recipes/met/runner.sh
#146 #147 #148 #149
Still has uploading commented out, as we don't yet have a Sharepoint page for the Met data. Also does not include scheduler.
> Create four Met tables

- .github/workflows/cuebiq_homeswitcher.yml
- recipes/cuebiq/create_homeswitcher.sql
- recipes/cuebiq/runner.sh
- recipes/cuebiq/runner_homeswitcher.sh
> adding homeswitcher

- .github/workflows/met.yml
- recipes/met/runner.sh
Currently set for 1st and 15th of the month
> Add MET scheduler

- recipes/foursquare/create_zipcode.sql
- recipes/foursquare/datacube.py
- change data-cube2 to data-cube4
- convert "" to null::numeric
> switching to new google drive folder and adding data cleaning in sql

- recipes/street_easy/build_rental_sales_index.py
> 169 -- Test PR adding comments

- recipes/foursquare/datacube.py
#186 please review. .env will need to be changed in production. Changes confirmed in dev database.
> 186 foursquare relink gdrive

- bin/axway.sh
> combining linked-in changes with met changes.

- bin/run.sh
- recipes/foursquare/datacube.py
- recipes/met/runner.sh
#192 Changed the folder. Need to change the credentials in the Github secrets.
> 192 met and axway

- bin/axway.sh
- bin/run.sh
- recipes/linkedin/runner.sh
- recipes/mastercard/file.transfer.test.txt
- recipes/met/runner.sh
#192 #195 #191  #193 
Removed debugging commands that were causing axway_ls to crash.
Commented out exit on crash. That was for debugging.
Met can now be executed through runner in Digital Ocean environment via ```./rdp run cloud met```
Specify where axway_ls fails in debugging.
> 192 2 axway cont

- recipes/met/runner.sh
#195 #192 #191
added && to met to catch errors.
> added && to met to catch errors.

- recipes/linkedin/runner.sh
- recipes/met/runner.sh
#192
#193 
#195 
The error checking && broke the code. Should use | instead.
> removed && and replaced with |

- recipes/met/dedup.py
- recipes/met/runner.sh
Need to check if files pushed to sharepoint are correct.
> add code to dedup records and save combined file to axway

- bin/sharepoint.py
#201 #202  Simplified check for empty table as per Yulia's suggestions.
> 201 blank csvs

- .github/workflows/mastercard.yml
- bin/run.sh
- recipes/mastercard/runner.sh
#196 
Will back up Mastercard files to AWS S3.
> 196 mastercard

- bin/run.sh
- recipes/cuebiq/runner.sh
- recipes/cuebiq/runner_travelers.sh
#211 #213 
General change to all apps to send error messages in runners to stdout, with explicit error handling in cuebiq to write error messages to stdout.
> send loging messages to stdout for all apps and also for cuebiq

- recipes/mastercard/runner.sh
> instead of uploading all files, uploads only the most recent .zip file.

- recipes/mastercard/runner.sh
#219 #222
Pulls the latest file in the Mastercard sftp site and uploads it to a folder with the date, 'all_data', and 'latest'. Warning: if there are more than one file on the Mastercard server, only the latest will upload.
Cleaned up the pushing and popping of the input directory. It goes into the input directory, does its work, and leaves.
> 219 multiple mastercard files upload

- .github/workflows/betanyc.yml
- .github/workflows/cuebiq_daily.yml
- .github/workflows/cuebiq_homeswitcher.yml
- .github/workflows/cuebiq_mobility.yml
- .github/workflows/cuebiq_travelers.yml
- .github/workflows/cuebiq_weekly.yml
- .github/workflows/docker_image.yml
- .github/workflows/foursquare_county.yml
- .github/workflows/foursquare_zipcode.yml
- .github/workflows/ioby.yml
- .github/workflows/kinsa.yml
- .github/workflows/linkedin.yml
- .github/workflows/mastercard.yml
- .github/workflows/met.yml
- .github/workflows/oats.yml
- .github/workflows/opp_insights_daily.yml
- .github/workflows/opp_insights_weekly.yml
- .github/workflows/street_easy.yml
- .github/workflows/upsolve.yml
- .github/workflows/versions.yml
Removed notifications from decommissioned workflows
> Slack notifications

- .github/workflows/cuebiq_daily.yml
- .github/workflows/cuebiq_homeswitcher.yml
- .github/workflows/cuebiq_mobility.yml
- .github/workflows/cuebiq_travelers.yml
- .github/workflows/cuebiq_weekly.yml
- .github/workflows/foursquare_county.yml
- .github/workflows/foursquare_zipcode.yml
- .github/workflows/ioby.yml
- .github/workflows/kinsa.yml
- .github/workflows/mastercard.yml
- .github/workflows/oats.yml
- .github/workflows/opp_insights_daily.yml
- .github/workflows/opp_insights_weekly.yml
- .github/workflows/street_easy.yml
- .github/workflows/upsolve.yml
- .github/workflows/versions.yml
#240 can now execute code from github actions.
> Mastercard upload all

- recipes/mastercard/aws.py
- recipes/mastercard/runner.sh
- recipes/mastercard/save_mastercard_master_csv.py
We are still facing outages with Sharepoint, but the runner executed the code successfully up to the sharepoint failure.
> Mastercard csv extract aws

- recipes/foursquare/datacube.py
- recipes/foursquare/runner_county_2.sh
The version for county is now taken from county, not zipcode.
> 253 foursquare county

- recipes/mastercard/save_mastercard_master_csv.py
This table is scheduled to update via Athena.
> changed to mep_mastercard_processed.

- recipes/linkedin/build.py
- recipes/linkedin/runner.sh
Just make sure to convert xlsx to CSV or operation will fail.
> changed from reading xlsx to reading csv.

- recipes/mastercard/runner.sh
> #263 Mastercard stop creating folders, create a latest file, create csvs not zips.

- recipes/mastercard/runner.sh
> 263 mastercard sharepoint

- recipes/mastercard_no_proxy/runner.sh
bring outside proxy changes back into master
> Mastercard outside proxy
